use std::fmt::Write;

use crate::matrix::{Builder, Language, Matrix, Package};

// ---------------------------------------------------------------------------
// sources.nix
// ---------------------------------------------------------------------------

/// Generate the `lib/sources.nix` file content from the matrix.
#[must_use]
pub fn generate_sources_nix(matrix: &Matrix) -> String {
    let mut out = String::new();
    out.push_str(
        "# Centralized source definitions for all buildable akeyless repos.\n\
         # !! AUTO-GENERATED by akeyless-matrix generate \u{2014} do not edit manually !!\n\
         # Uses substrate's mkSourceRegistry pattern.\n\
         { mkSourceRegistry, fetchFromGitHub }:\n\
         mkSourceRegistry {\n\
         \x20 inherit fetchFromGitHub;\n\
         \x20 repos = {\n",
    );

    let tiers: [(u8, &str); 3] = [
        (1, "Tier 1: Daily tools"),
        (2, "Tier 2: Dev tools"),
        (3, "Tier 3: SDKs"),
    ];

    for (tier_num, tier_label) in &tiers {
        let tier_pkgs: Vec<(&String, &Package)> = matrix
            .packages
            .iter()
            .filter(|(_, p)| p.tier == *tier_num && p.builder != Builder::Fetchurl)
            .collect();

        if tier_pkgs.is_empty() {
            continue;
        }

        let _ = writeln!(
            out,
            "    # \u{2500}\u{2500} {tier_label} \u{2500}{}\u{2500}",
            "\u{2500}".repeat(50 - tier_label.len())
        );

        for (pkg_name, pkg) in &tier_pkgs {
            let verified = Matrix::all_verified(pkg);
            let latest = Matrix::latest_verified(pkg);

            for (ver, entry) in &verified {
                let Some(ref source_hash) = entry.source_hash else {
                    continue;
                };
                let base_key = Matrix::source_key(pkg_name);
                let is_latest = latest.is_some_and(|(lv, _)| lv == *ver);
                let key = if is_latest {
                    base_key.clone()
                } else {
                    format!("{}-{}", base_key, Matrix::sanitize_version(ver))
                };

                let fork_comment = pkg
                    .fork_of
                    .as_ref()
                    .map_or(String::new(), |_| {
                        let reason = pkg.fork_reason.as_deref().unwrap_or("fork");
                        format!(" # fork: {reason}")
                    });

                let _ = writeln!(out, "    {key} = {{");
                let _ = writeln!(
                    out,
                    "      owner = \"{owner}\"; repo = \"{repo}\";{fork_comment}",
                    owner = pkg.owner,
                    repo = pkg.repo,
                );
                let _ = writeln!(out, "      rev = \"{rev}\";", rev = entry.rev);
                let _ = writeln!(out, "      hash = \"{source_hash}\";");
                let _ = writeln!(out, "      version = \"{ver}\";");
                let _ = writeln!(out, "    }};");
            }
        }
    }

    out.push_str("  };\n}\n");
    out
}

// ---------------------------------------------------------------------------
// builds/go/default.nix
// ---------------------------------------------------------------------------

/// Generate the `builds/go/default.nix` file content from the matrix.
#[must_use]
pub fn generate_go_builds(matrix: &Matrix) -> String {
    let mut out = String::new();
    out.push_str("# All Go package builds for akeyless repos.\n");
    out.push_str("# !! AUTO-GENERATED by akeyless-matrix generate \u{2014} do not edit manually !!\n");
    out.push_str("# Tools use substrate's mkGoTool. Libraries use substrate's mkGoLibraryCheck.\n");
    out.push_str("{ pkgs, sources, mkGoTool, mkGoLibraryCheck }:\n");
    out.push_str("let\n");
    out.push_str("  # Version helper \u{2014} reads from source registry metadata\n");
    out.push_str("  v = name: sources.${name}.meta.version;\n\n");
    out.push_str("  # Shared defaults for all akeyless Go tools\n");
    out.push_str("  mkAkeylessTool = name: args: mkGoTool pkgs ({\n");
    out.push_str("    version = v name;\n");
    out.push_str("    src = sources.${name};\n");
    out.push_str("    doCheck = false;\n");
    out.push_str("    license = pkgs.lib.licenses.asl20;\n");
    out.push_str("  } // args);\n\n");
    out.push_str("  # Shared defaults for all akeyless Go library checks\n");
    out.push_str("  mkAkeylessLibCheck = name: args: mkGoLibraryCheck pkgs ({\n");
    out.push_str("    version = v name;\n");
    out.push_str("    src = sources.${name};\n");
    out.push_str("    license = pkgs.lib.licenses.asl20;\n");
    out.push_str("  } // args);\n");
    out.push_str("in {\n");

    let tiers: [(u8, &str); 3] = [
        (1, "Tier 1: Daily tools"),
        (2, "Tier 2: Dev tools"),
        (3, "Tier 2/3: Libraries (build check via substrate mkGoLibraryCheck)"),
    ];

    for (tier_num, tier_label) in &tiers {
        let go_pkgs: Vec<(&String, &Package)> = matrix
            .packages
            .iter()
            .filter(|(_, p)| {
                p.language == Language::Go && {
                    if *tier_num == 3 {
                        // Tier 3 section includes library checks from tier 2 and 3
                        (p.tier == 2 || p.tier == 3)
                            && p.builder == Builder::MkGoLibraryCheck
                    } else {
                        p.tier == *tier_num && p.builder == Builder::MkGoTool
                    }
                }
            })
            .collect();

        if go_pkgs.is_empty() {
            continue;
        }

        let _ = writeln!(
            out,
            "  # \u{2500}\u{2500} {tier_label} \u{2500}{}\u{2500}",
            "\u{2500}".repeat(50usize.saturating_sub(tier_label.len()))
        );
        out.push('\n');

        for (pkg_name, pkg) in &go_pkgs {
            let verified = Matrix::all_verified(pkg);
            let latest = Matrix::latest_verified(pkg);

            for (ver, entry) in &verified {
                let base_key = Matrix::source_key(pkg_name);
                let is_latest = latest.is_some_and(|(lv, _)| lv == *ver);
                let (attr_name, src_key) = if is_latest {
                    (pkg_name.to_string(), base_key.clone())
                } else {
                    let san = Matrix::sanitize_version(ver);
                    (format!("{pkg_name}-{san}"), format!("{base_key}-{san}"))
                };

                if pkg.builder == Builder::MkGoTool {
                    write_go_tool_entry(&mut out, &attr_name, &src_key, pkg, entry);
                } else {
                    write_go_lib_check_entry(&mut out, &attr_name, &src_key, pkg, entry);
                }
            }
        }
    }

    out.push_str("}\n");
    out
}

fn write_go_tool_entry(
    out: &mut String,
    pkg_name: &str,
    key: &str,
    pkg: &Package,
    entry: &crate::matrix::VersionEntry,
) {
    let _ = writeln!(out, "  {pkg_name} = mkAkeylessTool \"{key}\" {{");
    let _ = writeln!(out, "    pname = \"{pkg_name}\";");

    // Vendor hash
    if let Some(ref vh) = entry.vendor_hash {
        let _ = writeln!(out, "    vendorHash = \"{vh}\";");
    } else {
        let _ = writeln!(out, "    vendorHash = null;");
    }

    // Proxy vendor
    if pkg.proxy_vendor.unwrap_or(false) {
        let _ = writeln!(out, "    proxyVendor = true;");
    }

    // Sub packages
    if let Some(ref sp) = pkg.sub_packages {
        let items: Vec<String> = sp.iter().map(|s| format!("\"{s}\"")).collect();
        let _ = writeln!(out, "    subPackages = [ {} ];", items.join(" "));
    }

    // Description and homepage
    let _ = writeln!(out, "    description = \"{}\";", nix_escape(&pkg.description));
    let _ = writeln!(out, "    homepage = \"{}\";", nix_escape(&pkg.homepage));

    // License override
    if let Some(ref lic) = pkg.license {
        let nix_license = license_to_nix(lic);
        let _ = writeln!(out, "    license = pkgs.lib.licenses.{nix_license};");
    }

    // Extra post install
    if let Some(ref epi) = pkg.extra_post_install {
        // Interpolate ${version} as ${v "key"}
        let interpolated = epi.replace("${version}", &format!("${{v \"{key}\"}}"));
        let _ = writeln!(out, "    extraPostInstall = ''");
        let _ = writeln!(out, "      {interpolated}");
        let _ = writeln!(out, "    '';");
    }

    let _ = writeln!(out, "  }};\n");
}

fn write_go_lib_check_entry(
    out: &mut String,
    pkg_name: &str,
    key: &str,
    pkg: &Package,
    entry: &crate::matrix::VersionEntry,
) {
    let _ = writeln!(out, "  {pkg_name} = mkAkeylessLibCheck \"{key}\" {{");
    let _ = writeln!(out, "    pname = \"{pkg_name}\";");

    // Vendor hash
    if let Some(ref vh) = entry.vendor_hash {
        let _ = writeln!(out, "    vendorHash = \"{vh}\";");
    } else {
        let _ = writeln!(out, "    vendorHash = null;");
    }

    // Proxy vendor
    if pkg.proxy_vendor.unwrap_or(false) {
        let _ = writeln!(out, "    proxyVendor = true;");
    }

    let _ = writeln!(out, "    description = \"{}\";", nix_escape(&pkg.description));
    let _ = writeln!(out, "    homepage = \"{}\";", nix_escape(&pkg.homepage));
    let _ = writeln!(out, "  }};\n");
}

// ---------------------------------------------------------------------------
// builds/rust/default.nix
// ---------------------------------------------------------------------------

/// Generate the `builds/rust/default.nix` file content from the matrix.
#[must_use]
pub fn generate_rust_builds(matrix: &Matrix) -> String {
    let mut out = String::new();
    out.push_str(
        "# Rust package builds for akeyless repos.\n\
         # !! AUTO-GENERATED by akeyless-matrix generate \u{2014} do not edit manually !!\n\
         { pkgs, sources }:\n\
         {\n",
    );

    for (pkg_name, pkg) in &matrix.packages {
        if pkg.language != Language::Rust {
            continue;
        }
        let verified = Matrix::all_verified(pkg);
        let latest = Matrix::latest_verified(pkg);

        for (ver, entry) in &verified {
            let base_key = Matrix::source_key(pkg_name);
            let is_latest = latest.is_some_and(|(lv, _)| lv == *ver);
            let (attr_name, src_key) = if is_latest {
                (pkg_name.to_string(), base_key.clone())
            } else {
                let san = Matrix::sanitize_version(ver);
                (format!("{pkg_name}-{san}"), format!("{base_key}-{san}"))
            };

            let _ = writeln!(out, "  {attr_name} = pkgs.rustPlatform.buildRustPackage {{");
            let _ = writeln!(out, "    pname = \"{attr_name}\";");
            let _ = writeln!(out, "    version = sources.{src_key}.meta.version;");
            let _ = writeln!(out, "    src = sources.{src_key};");

            if let Some(ref ch) = entry.cargo_hash {
                let _ = writeln!(out, "    cargoHash = \"{ch}\";");
            }

            let _ = writeln!(out, "    doCheck = false;");

            if let Some(ref inputs) = pkg.native_build_inputs {
                let items: Vec<String> = inputs.iter().map(|s| format!("pkgs.{s}")).collect();
                let _ = writeln!(out, "    nativeBuildInputs = [ {} ];", items.join(" "));
            }

            let _ = writeln!(out, "    meta = {{");
            let _ = writeln!(out, "      description = \"{}\";", nix_escape(&pkg.description));
            let _ = writeln!(out, "      homepage = \"{}\";", nix_escape(&pkg.homepage));
            let _ = writeln!(out, "      license = pkgs.lib.licenses.asl20;");
            let _ = writeln!(out, "    }};");
            let _ = writeln!(out, "  }};\n");
        }
    }

    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// builds/python/default.nix
// ---------------------------------------------------------------------------

/// Generate the `builds/python/default.nix` file content from the matrix.
#[must_use]
pub fn generate_python_builds(matrix: &Matrix) -> String {
    let mut out = String::new();
    out.push_str(
        "# Python package builds for akeyless repos.\n\
         # !! AUTO-GENERATED by akeyless-matrix generate \u{2014} do not edit manually !!\n\
         # Uses substrate's mkPythonPackage pattern.\n\
         { pkgs, sources, mkPythonPackage }:\n\
         {\n",
    );

    for (pkg_name, pkg) in &matrix.packages {
        if pkg.language != Language::Python {
            continue;
        }
        let verified = Matrix::all_verified(pkg);
        let latest = Matrix::latest_verified(pkg);

        for (ver, _entry) in &verified {
            let base_key = Matrix::source_key(pkg_name);
            let is_latest = latest.is_some_and(|(lv, _)| lv == *ver);
            let (attr_name, src_key) = if is_latest {
                (pkg_name.to_string(), base_key.clone())
            } else {
                let san = Matrix::sanitize_version(ver);
                (format!("{pkg_name}-{san}"), format!("{base_key}-{san}"))
            };
            let pname = pkg.pname_override.as_deref().unwrap_or(&attr_name);

            let _ = writeln!(out, "  {attr_name} = mkPythonPackage pkgs {{");
            let _ = writeln!(out, "    pname = \"{pname}\";");
            let _ = writeln!(out, "    version = sources.{src_key}.meta.version;");
            let _ = writeln!(out, "    src = sources.{src_key};");

            if let Some(ref deps) = pkg.python_deps {
                let _ = writeln!(out, "    propagatedBuildInputs = with pkgs.python3Packages; [");
                for dep in deps {
                    let _ = writeln!(out, "      {dep}");
                }
                let _ = writeln!(out, "    ];");
            }

            let _ = writeln!(out, "    description = \"{}\";", nix_escape(&pkg.description));
            let _ = writeln!(out, "    homepage = \"{}\";", nix_escape(&pkg.homepage));
            let _ = writeln!(out, "  }};\n");
        }
    }

    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// builds/typescript/default.nix
// ---------------------------------------------------------------------------

/// Generate the `builds/typescript/default.nix` file content from the matrix.
#[must_use]
pub fn generate_typescript_builds(matrix: &Matrix) -> String {
    let mut out = String::new();
    out.push_str(
        "# TypeScript/Node package builds for akeyless repos.\n\
         # !! AUTO-GENERATED by akeyless-matrix generate \u{2014} do not edit manually !!\n\
         { pkgs, sources }:\n\
         {\n",
    );

    for (pkg_name, pkg) in &matrix.packages {
        if pkg.language != Language::TypeScript {
            continue;
        }
        let verified = Matrix::all_verified(pkg);
        let latest = Matrix::latest_verified(pkg);

        for (ver, entry) in &verified {
            let base_key = Matrix::source_key(pkg_name);
            let is_latest = latest.is_some_and(|(lv, _)| lv == *ver);
            let (attr_name, src_key) = if is_latest {
                (pkg_name.to_string(), base_key.clone())
            } else {
                let san = Matrix::sanitize_version(ver);
                (format!("{pkg_name}-{san}"), format!("{base_key}-{san}"))
            };

            let _ = writeln!(out, "  {attr_name} = pkgs.buildNpmPackage {{");
            let _ = writeln!(out, "    pname = \"{attr_name}\";");
            let _ = writeln!(out, "    version = sources.{src_key}.meta.version;");
            let _ = writeln!(out, "    src = sources.{src_key};");

            if let Some(ref nh) = entry.npm_deps_hash {
                let _ = writeln!(out, "    npmDepsHash = \"{nh}\";");
            }

            if pkg.dont_npm_build.unwrap_or(false) {
                let _ = writeln!(out, "    dontNpmBuild = true;");
            }

            let _ = writeln!(out, "    meta = {{");
            let _ = writeln!(out, "      description = \"{}\";", nix_escape(&pkg.description));
            let _ = writeln!(out, "      homepage = \"{}\";", nix_escape(&pkg.homepage));
            let _ = writeln!(out, "      license = pkgs.lib.licenses.asl20;");
            let _ = writeln!(out, "    }};");
            let _ = writeln!(out, "  }};\n");
        }
    }

    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// builds/binary/default.nix
// ---------------------------------------------------------------------------

/// Generate `builds/binary/default.nix` from binary packages in the matrix.
#[must_use]
pub fn generate_binary_builds(matrix: &Matrix) -> String {
    let mut out = String::new();
    out.push_str(
        "# Prebuilt binary packages for akeyless closed-source tools.\n\
         # !! AUTO-GENERATED by akeyless-matrix generate \u{2014} do not edit manually !!\n\
         { pkgs }:\n\
         let\n\
         \x20 system = pkgs.stdenv.hostPlatform.system;\n\
         in {\n",
    );

    for (pkg_name, pkg) in &matrix.packages {
        if pkg.builder != Builder::Fetchurl {
            continue;
        }
        let verified = Matrix::all_verified(pkg);
        let latest = Matrix::latest_verified(pkg);

        for (ver, entry) in &verified {
            let is_latest = latest.is_some_and(|(lv, _)| lv == *ver);
            let attr_name = if is_latest {
                pkg_name.to_string()
            } else {
                format!("{}-{}", pkg_name, Matrix::sanitize_version(ver))
            };

            let binary_name = pkg.binary_name.as_deref().unwrap_or(pkg_name);
            let license_nix = pkg.license.as_deref().map_or("unfree", |l| match l {
                "unfree" => "unfree",
                "MIT" => "mit",
                "Apache-2.0" => "asl20",
                _ => "free",
            });

            // Build the platform sources attrset
            let mut platforms = String::new();
            let platform_hashes = [
                ("aarch64-darwin", &entry.hash_aarch64_darwin),
                ("x86_64-darwin", &entry.hash_x86_64_darwin),
                ("x86_64-linux", &entry.hash_x86_64_linux),
                ("aarch64-linux", &entry.hash_aarch64_linux),
            ];

            if let Some(ref urls) = pkg.platform_urls {
                for (plat, hash_opt) in &platform_hashes {
                    if let (Some(url), Some(hash)) = (urls.get(*plat), hash_opt) {
                        let _ = writeln!(
                            platforms,
                            "      \"{plat}\" = {{ url = \"{url}\"; hash = \"{hash}\"; }};"
                        );
                    }
                }
            }

            let _ = writeln!(out, "  {attr_name} = let");
            let _ = writeln!(out, "    sources = {{");
            out.push_str(&platforms);
            let _ = writeln!(out, "    }};");
            let _ = writeln!(
                out,
                "    src = sources.${{system}} or (throw \"{attr_name}: unsupported system ${{system}}\");"
            );
            let _ = writeln!(out, "  in pkgs.stdenv.mkDerivation {{");
            let _ = writeln!(out, "    pname = \"{attr_name}\";");
            let _ = writeln!(out, "    version = \"{ver}\";");
            let _ = writeln!(
                out,
                "    src = pkgs.fetchurl {{ inherit (src) url hash; }};"
            );
            let _ = writeln!(out, "    dontUnpack = true;");
            let _ = writeln!(
                out,
                "    nativeBuildInputs = pkgs.lib.optionals pkgs.stdenv.hostPlatform.isLinux [ pkgs.autoPatchelfHook ];"
            );
            let _ = writeln!(out, "    installPhase = ''");
            let _ = writeln!(out, "      mkdir -p $out/bin");
            let _ = writeln!(out, "      cp $src $out/bin/{binary_name}");
            let _ = writeln!(out, "      chmod +x $out/bin/{binary_name}");
            let _ = writeln!(out, "    '';");
            let _ = writeln!(out, "    meta = {{");
            let _ = writeln!(
                out,
                "      description = \"{}\";",
                nix_escape(&pkg.description)
            );
            let _ = writeln!(
                out,
                "      homepage = \"{}\";",
                nix_escape(&pkg.homepage)
            );
            let _ = writeln!(out, "      license = pkgs.lib.licenses.{license_nix};");
            let _ = writeln!(out, "      platforms = builtins.attrNames sources;");
            let _ = writeln!(out, "      mainProgram = \"{binary_name}\";");
            let _ = writeln!(out, "    }};");
            let _ = writeln!(out, "  }};\n");
        }
    }

    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// lib/matrix-metadata.nix
// ---------------------------------------------------------------------------

/// Generate the `lib/matrix-metadata.nix` file content from the matrix.
#[must_use]
pub fn generate_matrix_metadata(matrix: &Matrix) -> String {
    let mut out = String::new();
    out.push_str(
        "# !! AUTO-GENERATED by akeyless-matrix generate \u{2014} do not edit manually !!\n\
         # Exports packageSourceMap and tier lists for flake.nix and module/default.nix.\n\
         {\n",
    );

    // packageSourceMap — ALL versioned entries
    out.push_str("  packageSourceMap = {\n");
    for (pkg_name, pkg) in &matrix.packages {
        let verified = Matrix::all_verified(pkg);
        let latest = Matrix::latest_verified(pkg);

        if pkg.builder == Builder::Fetchurl {
            // Binary packages use their own name as the source key
            if latest.is_some() {
                let _ = writeln!(out, "    {pkg_name} = \"{pkg_name}\";");
            }
            continue; // No versioned source keys for binaries
        }

        let base_key = Matrix::source_key(pkg_name);

        for (ver, _) in &verified {
            let is_latest = latest.is_some_and(|(lv, _)| lv == *ver);
            if is_latest {
                let _ = writeln!(out, "    {pkg_name} = \"{base_key}\";");
            } else {
                let san = Matrix::sanitize_version(ver);
                let _ = writeln!(out, "    {pkg_name}-{san} = \"{base_key}-{san}\";");
            }
        }
    }
    out.push_str("  };\n\n");

    // Tier lists
    let tiers: [(u8, &str); 3] = [
        (1, "tier1Packages"),
        (2, "tier2Packages"),
        (3, "tier3Packages"),
    ];

    for (tier_num, tier_name) in &tiers {
        let _ = writeln!(out, "  {tier_name} = [");
        for (pkg_name, pkg) in &matrix.packages {
            if pkg.tier == *tier_num {
                // Only include packages that have a buildable builder and at least
                // one verified version
                if pkg.builder != Builder::None && Matrix::latest_verified(pkg).is_some() {
                    let _ = writeln!(out, "    \"{pkg_name}\"");
                }
            }
        }
        let _ = writeln!(out, "  ];\n");
    }

    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Escape a string for use inside a Nix double-quoted string literal.
/// Handles backslash, double-quote, and dollar-brace (interpolation).
fn nix_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace("${", "\\${")
}

/// Map a license string (e.g., "MPL-2.0") to a nixpkgs license attribute name.
fn license_to_nix(license: &str) -> &str {
    match license {
        "MPL-2.0" => "mpl20",
        "MIT" => "mit",
        "Apache-2.0" => "asl20",
        "BSD-3-Clause" => "bsd3",
        "GPL-3.0" => "gpl3Only",
        _ => "free",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::matrix::{Builder, Language, Matrix, Package, Status, VersionEntry};
    use std::collections::BTreeMap;

    fn test_matrix() -> Matrix {
        let mut versions = BTreeMap::new();
        versions.insert(
            "1.0.0".to_string(),
            VersionEntry {
                rev: "abc123".into(),
                source_hash: Some("sha256-test".into()),
                vendor_hash: Some("sha256-vendor".into()),
                cargo_hash: None,
                npm_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-test".to_string(),
            Package {
                owner: "testorg".into(),
                repo: "test-repo".into(),
                language: Language::Go,
                builder: Builder::MkGoTool,
                tier: 1,
                sub_packages: Some(vec![".".into()]),
                proxy_vendor: None,
                license: None,
                description: "A test package".into(),
                homepage: "https://example.com".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: None,
                python_deps: None,
                pname_override: None,
                dont_npm_build: None,
                extra_post_install: None,
                binary_name: None,
                platform_urls: None,
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_sources_nix() {
        let matrix = test_matrix();
        let output = generate_sources_nix(&matrix);
        assert!(output.contains("mkSourceRegistry"));
        assert!(output.contains(r#"owner = "testorg"; repo = "test-repo";"#));
        assert!(output.contains(r#"hash = "sha256-test";"#));
        assert!(output.contains(r#"version = "1.0.0";"#));
    }

    #[test]
    fn test_generate_go_builds() {
        let matrix = test_matrix();
        let output = generate_go_builds(&matrix);
        assert!(output.contains("mkAkeylessTool"));
        assert!(output.contains(r#"vendorHash = "sha256-vendor";"#));
        assert!(output.contains(r#"subPackages = [ "." ];"#));
    }

    #[test]
    fn test_generate_matrix_metadata() {
        let matrix = test_matrix();
        let output = generate_matrix_metadata(&matrix);
        assert!(output.contains(r#"akeyless-test = "test";"#));
        assert!(output.contains("tier1Packages"));
        assert!(output.contains(r#""akeyless-test""#));
    }

    #[test]
    fn test_generate_go_builds_extra_post_install() {
        let mut matrix = test_matrix();
        let pkg = matrix.packages.get_mut("akeyless-test").unwrap();
        pkg.extra_post_install =
            Some("mv $out/bin/old $out/bin/new_v${version}".into());
        pkg.license = Some("MPL-2.0".into());

        let output = generate_go_builds(&matrix);
        assert!(output.contains("extraPostInstall = ''"));
        // ${version} should be interpolated to ${v "test"}
        assert!(output.contains(r#"${v "test"}"#));
        assert!(output.contains("license = pkgs.lib.licenses.mpl20;"));
    }

    #[test]
    fn test_generate_sources_fork_comment() {
        let mut matrix = test_matrix();
        let pkg = matrix.packages.get_mut("akeyless-test").unwrap();
        pkg.fork_of = Some("upstream/repo".into());
        pkg.fork_reason = Some("go mod tidy fix".into());

        let output = generate_sources_nix(&matrix);
        assert!(output.contains("# fork: go mod tidy fix"));
    }

    #[test]
    fn test_generate_go_builds_null_vendor_hash() {
        let mut matrix = test_matrix();
        let pkg = matrix.packages.get_mut("akeyless-test").unwrap();
        pkg.builder = Builder::MkGoLibraryCheck;
        pkg.tier = 3;
        // Remove vendor_hash to test null generation
        let ver = pkg.versions.get_mut("1.0.0").unwrap();
        ver.vendor_hash = None;

        let output = generate_go_builds(&matrix);
        assert!(output.contains("vendorHash = null;"));
        assert!(output.contains("mkAkeylessLibCheck"));
    }

    #[test]
    fn test_nix_escape() {
        assert_eq!(nix_escape("simple"), "simple");
        assert_eq!(nix_escape(r#"has "quotes""#), r#"has \"quotes\""#);
        assert_eq!(nix_escape("has ${interp}"), "has \\${interp}");
        assert_eq!(nix_escape(r"back\slash"), r"back\\slash");
    }

    #[test]
    fn test_generate_go_builds_description_with_special_chars() {
        let mut matrix = test_matrix();
        let pkg = matrix.packages.get_mut("akeyless-test").unwrap();
        pkg.description = r#"Tool for "fancy" operations"#.into();

        let output = generate_go_builds(&matrix);
        assert!(output.contains(r#"description = "Tool for \"fancy\" operations";"#));
    }

    /// Helper: create a matrix with TWO verified versions for a single Go package.
    fn test_matrix_multi_version() -> Matrix {
        let mut versions = BTreeMap::new();
        versions.insert(
            "0.6.1".to_string(),
            VersionEntry {
                rev: "aaa111".into(),
                source_hash: Some("sha256-old".into()),
                vendor_hash: Some("sha256-vendorold".into()),
                cargo_hash: None,
                npm_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );
        versions.insert(
            "0.7.0".to_string(),
            VersionEntry {
                rev: "bbb222".into(),
                source_hash: Some("sha256-new".into()),
                vendor_hash: Some("sha256-vendornew".into()),
                cargo_hash: None,
                npm_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );
        // A pending version should NOT appear
        versions.insert(
            "0.8.0".to_string(),
            VersionEntry {
                rev: "ccc333".into(),
                source_hash: Some("sha256-pending".into()),
                vendor_hash: None,
                cargo_hash: None,
                npm_deps_hash: None,
                status: Status::Pending,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-test".to_string(),
            Package {
                owner: "testorg".into(),
                repo: "test-repo".into(),
                language: Language::Go,
                builder: Builder::MkGoTool,
                tier: 1,
                sub_packages: Some(vec![".".into()]),
                proxy_vendor: None,
                license: None,
                description: "A test package".into(),
                homepage: "https://example.com".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: None,
                python_deps: None,
                pname_override: None,
                dont_npm_build: None,
                extra_post_install: None,
                binary_name: None,
                platform_urls: None,
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_sources_nix_multi_version() {
        let matrix = test_matrix_multi_version();
        let output = generate_sources_nix(&matrix);

        // Latest (0.7.0) gets the bare key "test"
        assert!(output.contains("test = {"));
        assert!(output.contains(r#"version = "0.7.0";"#));
        assert!(output.contains(r#"hash = "sha256-new";"#));

        // Historical (0.6.1) gets versioned key "test-0_6_1"
        assert!(output.contains("test-0_6_1 = {"));
        assert!(output.contains(r#"version = "0.6.1";"#));
        assert!(output.contains(r#"hash = "sha256-old";"#));

        // Pending (0.8.0) should NOT appear
        assert!(!output.contains("0.8.0"));
        assert!(!output.contains("sha256-pending"));
    }

    #[test]
    fn test_generate_go_builds_multi_version() {
        let matrix = test_matrix_multi_version();
        let output = generate_go_builds(&matrix);

        // Latest gets bare name
        assert!(output.contains(r#"akeyless-test = mkAkeylessTool "test""#));
        assert!(output.contains(r#"vendorHash = "sha256-vendornew";"#));

        // Historical gets versioned name
        assert!(output.contains(r#"akeyless-test-0_6_1 = mkAkeylessTool "test-0_6_1""#));
        assert!(output.contains(r#"vendorHash = "sha256-vendorold";"#));

        // Pending should NOT appear
        assert!(!output.contains("0_8_0"));
    }

    #[test]
    fn test_generate_matrix_metadata_multi_version() {
        let matrix = test_matrix_multi_version();
        let output = generate_matrix_metadata(&matrix);

        // packageSourceMap has both entries
        assert!(output.contains(r#"akeyless-test = "test";"#));
        assert!(output.contains(r#"akeyless-test-0_6_1 = "test-0_6_1";"#));

        // Tier list only has unversioned (latest) name
        assert!(output.contains(r#""akeyless-test""#));
        // Versioned name should NOT be in tier lists
        assert!(!output.contains(r#""akeyless-test-0_6_1""#));
    }
}

