//! The Nix files `generate` writes into blackmatter-akeyless.
//!
//! Every file is a typed [`gen_nix::NixValue`] tree rendered by gen-nix's
//! one pretty-printer; no Nix syntax is assembled from strings here. The
//! layout siblings (`LaidOut*`, comments, blank entries) exist so the
//! rendered files keep the hand-tuned shape reviewers read.

use gen_nix::{
    AttrKey, AttrSetEntry, CollectionLayout, LambdaLayout, LetBinding, LetLayout, NixBinOp,
    NixValue, StrPart, bind, destructured, entry, inherit, render_file, str_entry,
};

use crate::matrix::{Builder, Language, Matrix, Package, VersionEntry};

/// Second header line of every generated file.
const AUTO_GENERATED: &str =
    "!! AUTO-GENERATED by akeyless-matrix generate \u{2014} do not edit manually !!";

// ---------------------------------------------------------------------------
// Shared shapes
// ---------------------------------------------------------------------------

/// One verified version of a package, with the attribute and source-key
/// names it is published under: the latest verified version takes the bare
/// names, older ones a `-<sanitized version>` suffix.
struct Release<'a> {
    pkg_name: &'a str,
    version: &'a str,
    entry: &'a VersionEntry,
    attr_name: String,
    src_key: String,
}

fn releases<'a>(pkg_name: &'a str, pkg: &'a Package) -> Vec<Release<'a>> {
    let latest = Matrix::latest_verified(pkg).map(|(v, _)| v);
    let base_key = Matrix::source_key(pkg_name);
    Matrix::all_verified(pkg)
        .into_iter()
        .map(|(version, entry)| {
            let (attr_name, src_key) = if latest == Some(version) {
                (pkg_name.to_string(), base_key.clone())
            } else {
                let san = Matrix::sanitize_version(version);
                (format!("{pkg_name}-{san}"), format!("{base_key}-{san}"))
            };
            Release {
                pkg_name,
                version,
                entry,
                attr_name,
                src_key,
            }
        })
        .collect()
}

/// A whole generated file: header comments, then a function over
/// `params` whose body starts on the next line.
fn nix_file(header: &[&str], params: &[&str], body: NixValue) -> String {
    render_file(&NixValue::commented(
        header.iter().copied(),
        NixValue::lambda_laid_out(
            LambdaLayout::BodyOnNextLine,
            destructured(params.iter().copied(), false),
            body,
        ),
    ))
}

/// Attrset with one entry per line, `{` newline `}` when empty.
fn block(entries: impl IntoIterator<Item = AttrSetEntry>) -> NixValue {
    NixValue::attrset_laid_out(CollectionLayout::Block, entries)
}

/// The canonical (block) attrset over typed entries.
fn attrs(entries: impl IntoIterator<Item = AttrSetEntry>) -> NixValue {
    NixValue::AttrSet {
        recursive: false,
        entries: entries.into_iter().collect(),
    }
}

fn s(value: &str) -> NixValue {
    NixValue::str(value)
}

fn path(parts: &[&str]) -> NixValue {
    NixValue::attr_path(parts.iter().copied())
}

fn call(func: NixValue, args: impl IntoIterator<Item = NixValue>) -> NixValue {
    NixValue::apply(func, args)
}

fn nix_license(attr: &str) -> NixValue {
    path(&["pkgs", "lib", "licenses", attr])
}

/// `sources.<key>.meta.version`
fn source_version(src_key: &str) -> NixValue {
    path(&["sources", src_key, "meta", "version"])
}

/// `sources.<key>`
fn source(src_key: &str) -> NixValue {
    path(&["sources", src_key])
}

/// `── <label> ────…─` section rule, padded to a fixed width.
fn tier_rule(label: &str) -> String {
    format!(
        "\u{2500}\u{2500} {label} \u{2500}{}\u{2500}",
        "\u{2500}".repeat(50usize.saturating_sub(label.len()))
    )
}

/// `name = value;` followed by an empty line: the per-package spacing of
/// every builds file.
fn spaced(name: &str, value: NixValue) -> [AttrSetEntry; 2] {
    [entry(name, value), AttrSetEntry::Blank]
}

/// Every verified release of every package `keep` selects, as spaced
/// entries built by `build`.
fn release_entries(
    matrix: &Matrix,
    keep: impl Fn(&Package) -> bool,
    build: impl Fn(&Package, &Release) -> NixValue,
) -> Vec<AttrSetEntry> {
    matrix
        .packages
        .iter()
        .filter(|(_, pkg)| keep(pkg))
        .flat_map(|(pkg_name, pkg)| {
            releases(pkg_name, pkg)
                .into_iter()
                .flat_map(|rel| spaced(&rel.attr_name, build(pkg, &rel)))
                .collect::<Vec<_>>()
        })
        .collect()
}

fn description_homepage(pkg: &Package) -> [AttrSetEntry; 2] {
    [
        entry("description", s(&pkg.description)),
        entry("homepage", s(&pkg.homepage)),
    ]
}

/// `meta = { description; homepage; license = asl20; }`
fn asl20_meta(pkg: &Package) -> AttrSetEntry {
    entry(
        "meta",
        attrs(
            description_homepage(pkg)
                .into_iter()
                .chain([entry("license", nix_license("asl20"))]),
        ),
    )
}

/// A literal-only indented string, one element per line.
fn indented(lines: &[String]) -> NixValue {
    NixValue::IndentedInterpolatedStr(
        lines
            .iter()
            .map(|l| vec![StrPart::Literal(l.clone())])
            .collect(),
    )
}

// ---------------------------------------------------------------------------
// sources.nix
// ---------------------------------------------------------------------------

/// Generate the `lib/sources.nix` file content from the matrix.
#[must_use]
pub fn generate_sources_nix(matrix: &Matrix) -> String {
    let tiers: [(u8, &str); 3] = [
        (1, "Tier 1: Daily tools"),
        (2, "Tier 2: Dev tools"),
        (3, "Tier 3: SDKs"),
    ];

    let mut repos = Vec::new();
    for (tier_num, tier_label) in tiers {
        let tier_pkgs: Vec<(&String, &Package)> = matrix
            .packages
            .iter()
            .filter(|(_, p)| p.tier == tier_num && p.builder != Builder::Fetchurl)
            .collect();
        if tier_pkgs.is_empty() {
            continue;
        }
        repos.push(AttrSetEntry::Comment(tier_rule(tier_label)));

        for (pkg_name, pkg) in tier_pkgs {
            let fork_comment = pkg
                .fork_of
                .as_ref()
                .map(|_| format!("fork: {}", pkg.fork_reason.as_deref().unwrap_or("fork")));
            for rel in releases(pkg_name, pkg) {
                let Some(source_hash) = rel.entry.source_hash.as_deref() else {
                    continue;
                };
                repos.push(entry(
                    &rel.src_key,
                    attrs([
                        AttrSetEntry::Line {
                            entries: vec![
                                entry("owner", s(&pkg.owner)),
                                entry("repo", s(&pkg.repo)),
                            ],
                            comment: fork_comment.clone(),
                        },
                        entry("rev", s(&rel.entry.rev)),
                        entry("hash", s(source_hash)),
                        entry("version", s(rel.version)),
                    ]),
                ));
            }
        }
    }

    nix_file(
        &[
            "Centralized source definitions for all buildable akeyless repos.",
            AUTO_GENERATED,
            "Uses substrate's mkSourceRegistry pattern.",
        ],
        &["mkSourceRegistry", "fetchFromGitHub"],
        call(
            NixValue::ident("mkSourceRegistry"),
            [attrs([
                inherit(None, ["fetchFromGitHub"]),
                entry("repos", block(repos)),
            ])],
        ),
    )
}

// ---------------------------------------------------------------------------
// builds/go/default.nix
// ---------------------------------------------------------------------------

/// `name: args: <builder> pkgs ({ <defaults> } // args)`: the shared-defaults
/// wrapper every Go package entry is applied through.
fn go_defaults_wrapper(builder: &str, defaults: Vec<AttrSetEntry>) -> NixValue {
    NixValue::lambda_single(
        "name",
        NixValue::lambda_single(
            "args",
            call(
                NixValue::ident(builder),
                [
                    NixValue::ident("pkgs"),
                    NixValue::BinOp {
                        op: NixBinOp::Update,
                        left: Box::new(attrs(defaults)),
                        right: Box::new(NixValue::ident("args")),
                    },
                ],
            ),
        ),
    )
}

/// `version = v name; src = sources.${name};`
fn go_version_and_src() -> [AttrSetEntry; 2] {
    [
        entry(
            "version",
            call(NixValue::ident("v"), [NixValue::ident("name")]),
        ),
        entry(
            "src",
            NixValue::select(
                NixValue::ident("sources"),
                [AttrKey::Interp(NixValue::ident("name"))],
            ),
        ),
    ]
}

fn go_let_bindings() -> Vec<LetBinding> {
    let tool_defaults: Vec<AttrSetEntry> = go_version_and_src()
        .into_iter()
        .chain([
            entry("doCheck", NixValue::Bool(false)),
            entry("license", nix_license("asl20")),
            AttrSetEntry::Comment(
                "Upstream go.mod is not ours to edit, so rewrite a bare-minor `go 1.N`".into(),
            ),
            AttrSetEntry::Comment(
                "to `go 1.N.0` at build time instead of tracing the fix on every eval.".into(),
            ),
            entry("normalizeGoDirective", NixValue::Bool(true)),
        ])
        .collect();
    let lib_check_defaults: Vec<AttrSetEntry> = go_version_and_src()
        .into_iter()
        .chain([entry("license", nix_license("asl20"))])
        .collect();

    vec![
        LetBinding::Comment("Version helper \u{2014} reads from source registry metadata".into()),
        bind(
            "v",
            NixValue::lambda_single(
                "name",
                NixValue::select(
                    NixValue::ident("sources"),
                    [
                        AttrKey::Interp(NixValue::ident("name")),
                        AttrKey::Ident("meta".into()),
                        AttrKey::Ident("version".into()),
                    ],
                ),
            ),
        ),
        LetBinding::Blank,
        LetBinding::Comment("Shared defaults for all akeyless Go tools".into()),
        bind(
            "mkAkeylessTool",
            go_defaults_wrapper("mkGoTool", tool_defaults),
        ),
        LetBinding::Blank,
        LetBinding::Comment("Shared defaults for all akeyless Go library checks".into()),
        bind(
            "mkAkeylessLibCheck",
            go_defaults_wrapper("mkGoLibraryCheck", lib_check_defaults),
        ),
    ]
}

/// Generate the `builds/go/default.nix` file content from the matrix.
#[must_use]
pub fn generate_go_builds(matrix: &Matrix) -> String {
    let tiers: [(u8, &str); 3] = [
        (1, "Tier 1: Daily tools"),
        (2, "Tier 2: Dev tools"),
        (
            3,
            "Tier 2/3: Libraries (build check via substrate mkGoLibraryCheck)",
        ),
    ];

    let mut body = Vec::new();
    for (tier_num, tier_label) in tiers {
        let in_tier = |p: &Package| {
            p.language == Language::Go
                && if tier_num == 3 {
                    // Tier 3 section includes library checks from tier 2 and 3
                    (p.tier == 2 || p.tier == 3) && p.builder == Builder::MkGoLibraryCheck
                } else {
                    p.tier == tier_num && p.builder == Builder::MkGoTool
                }
        };
        let entries = release_entries(matrix, in_tier, |pkg, rel| {
            if pkg.builder == Builder::MkGoTool {
                go_tool_entry(pkg, rel)
            } else {
                go_lib_check_entry(pkg, rel)
            }
        });
        if entries.is_empty() {
            continue;
        }
        body.push(AttrSetEntry::Comment(tier_rule(tier_label)));
        body.push(AttrSetEntry::Blank);
        body.extend(entries);
    }

    nix_file(
        &[
            "All Go package builds for akeyless repos.",
            AUTO_GENERATED,
            "Tools use substrate's mkGoTool. Libraries use substrate's mkGoLibraryCheck.",
        ],
        &["pkgs", "sources", "mkGoTool", "mkGoLibraryCheck"],
        NixValue::let_laid_out(LetLayout::BodyAfterIn, go_let_bindings(), block(body)),
    )
}

/// `pname`, `vendorHash` and (when set) `proxyVendor`: the head every Go
/// entry shares.
fn go_entry_head(pkg: &Package, rel: &Release) -> Vec<AttrSetEntry> {
    let mut entries = vec![
        entry("pname", s(&rel.attr_name)),
        entry(
            "vendorHash",
            rel.entry.vendor_hash.as_deref().map_or(NixValue::Null, s),
        ),
    ];
    if pkg.proxy_vendor.unwrap_or(false) {
        entries.push(entry("proxyVendor", NixValue::Bool(true)));
    }
    entries
}

fn go_tool_entry(pkg: &Package, rel: &Release) -> NixValue {
    let mut entries = go_entry_head(pkg, rel);
    if let Some(sp) = &pkg.sub_packages {
        entries.push(entry(
            "subPackages",
            NixValue::list_laid_out(CollectionLayout::Inline, sp.iter().map(|p| s(p))),
        ));
    }
    entries.extend(description_homepage(pkg));
    if let Some(lic) = &pkg.license {
        entries.push(entry("license", nix_license(license_to_nix(lic))));
    }
    if let Some(epi) = &pkg.extra_post_install {
        entries.push(entry("extraPostInstall", post_install(epi, &rel.src_key)));
    }
    call(
        NixValue::ident("mkAkeylessTool"),
        [s(&rel.src_key), attrs(entries)],
    )
}

/// `extra_post_install` as an indented string, each `${version}` becoming
/// an interpolation of this release's version, `${v "<key>"}`.
fn post_install(script: &str, src_key: &str) -> NixValue {
    let version = || call(NixValue::ident("v"), [s(src_key)]);
    NixValue::IndentedInterpolatedStr(
        script
            .lines()
            .map(|line| {
                let mut parts = Vec::new();
                for (i, literal) in line.split("${version}").enumerate() {
                    if i > 0 {
                        parts.push(StrPart::Interp(version()));
                    }
                    if !literal.is_empty() {
                        parts.push(StrPart::Literal(literal.to_string()));
                    }
                }
                parts
            })
            .collect(),
    )
}

fn go_lib_check_entry(pkg: &Package, rel: &Release) -> NixValue {
    let mut entries = go_entry_head(pkg, rel);
    entries.extend(description_homepage(pkg));
    call(
        NixValue::ident("mkAkeylessLibCheck"),
        [s(&rel.src_key), attrs(entries)],
    )
}

// ---------------------------------------------------------------------------
// builds/rust/default.nix
// ---------------------------------------------------------------------------

/// Generate the `builds/rust/default.nix` file content from the matrix.
#[must_use]
pub fn generate_rust_builds(matrix: &Matrix) -> String {
    let body = release_entries(
        matrix,
        |p| p.language == Language::Rust,
        |pkg, rel| {
            let mut entries = vec![
                entry("pname", s(&rel.attr_name)),
                entry("version", source_version(&rel.src_key)),
                entry("src", source(&rel.src_key)),
            ];
            if let Some(ch) = &rel.entry.cargo_hash {
                entries.push(entry("cargoHash", s(ch)));
            }
            entries.push(entry("doCheck", NixValue::Bool(false)));
            if let Some(inputs) = &pkg.native_build_inputs {
                entries.push(entry(
                    "nativeBuildInputs",
                    NixValue::list_laid_out(
                        CollectionLayout::Inline,
                        inputs.iter().map(|i| path(&["pkgs", i])),
                    ),
                ));
            }
            entries.push(asl20_meta(pkg));
            call(
                path(&["pkgs", "rustPlatform", "buildRustPackage"]),
                [attrs(entries)],
            )
        },
    );
    nix_file(
        &["Rust package builds for akeyless repos.", AUTO_GENERATED],
        &["pkgs", "sources"],
        block(body),
    )
}

// ---------------------------------------------------------------------------
// builds/python/default.nix
// ---------------------------------------------------------------------------

/// Generate the `builds/python/default.nix` file content from the matrix.
#[must_use]
pub fn generate_python_builds(matrix: &Matrix) -> String {
    let body = release_entries(
        matrix,
        |p| p.language == Language::Python,
        |pkg, rel| {
            let pname = pkg.pname_override.as_deref().unwrap_or(&rel.attr_name);
            let mut entries = vec![
                entry("pname", s(pname)),
                entry("version", source_version(&rel.src_key)),
                entry("src", source(&rel.src_key)),
            ];
            if let Some(deps) = &pkg.python_deps {
                entries.push(entry(
                    "propagatedBuildInputs",
                    NixValue::With {
                        scope: Box::new(path(&["pkgs", "python3Packages"])),
                        body: Box::new(NixValue::list_laid_out(
                            CollectionLayout::Block,
                            deps.iter().map(|d| NixValue::ident(d.as_str())),
                        )),
                    },
                ));
            }
            entries.extend(description_homepage(pkg));
            call(
                NixValue::ident("mkPythonPackage"),
                [NixValue::ident("pkgs"), attrs(entries)],
            )
        },
    );
    nix_file(
        &[
            "Python package builds for akeyless repos.",
            AUTO_GENERATED,
            "Uses substrate's mkPythonPackage pattern.",
        ],
        &["pkgs", "sources", "mkPythonPackage"],
        block(body),
    )
}

// ---------------------------------------------------------------------------
// builds/typescript/default.nix
// ---------------------------------------------------------------------------

/// Generate the `builds/typescript/default.nix` file content from the matrix.
#[must_use]
pub fn generate_typescript_builds(matrix: &Matrix) -> String {
    let body = release_entries(
        matrix,
        |p| p.language == Language::TypeScript,
        |pkg, rel| {
            let mut entries = vec![
                entry("pname", s(&rel.attr_name)),
                entry("version", source_version(&rel.src_key)),
                entry("src", source(&rel.src_key)),
            ];
            if let Some(nh) = &rel.entry.npm_deps_hash {
                entries.push(entry("npmDepsHash", s(nh)));
            }
            if pkg.dont_npm_build.unwrap_or(false) {
                entries.push(entry("dontNpmBuild", NixValue::Bool(true)));
            }
            entries.push(asl20_meta(pkg));
            call(path(&["pkgs", "buildNpmPackage"]), [attrs(entries)])
        },
    );
    nix_file(
        &[
            "TypeScript/Node package builds for akeyless repos.",
            AUTO_GENERATED,
        ],
        &["pkgs", "sources"],
        block(body),
    )
}

// ---------------------------------------------------------------------------
// builds/binary/default.nix
// ---------------------------------------------------------------------------

/// Generate `builds/binary/default.nix` from binary packages in the matrix.
#[must_use]
pub fn generate_binary_builds(matrix: &Matrix) -> String {
    let body = release_entries(matrix, |p| p.builder == Builder::Fetchurl, binary_entry);
    nix_file(
        &[
            "Prebuilt binary packages for akeyless closed-source tools.",
            AUTO_GENERATED,
        ],
        &["pkgs"],
        NixValue::let_laid_out(
            LetLayout::BodyAfterIn,
            [bind(
                "system",
                path(&["pkgs", "stdenv", "hostPlatform", "system"]),
            )],
            block(body),
        ),
    )
}

fn binary_entry(pkg: &Package, rel: &Release) -> NixValue {
    let attr_name = rel.attr_name.as_str();
    let binary_name = pkg.binary_name.as_deref().unwrap_or(rel.pkg_name);
    let entry_hashes = rel.entry;
    let platform_hashes = [
        ("aarch64-darwin", &entry_hashes.hash_aarch64_darwin),
        ("x86_64-darwin", &entry_hashes.hash_x86_64_darwin),
        ("x86_64-linux", &entry_hashes.hash_x86_64_linux),
        ("aarch64-linux", &entry_hashes.hash_aarch64_linux),
    ];

    // One `"<platform>" = { url; hash; };` per platform with both a URL
    // template and a hash; `{version}` in the template is this release.
    let platforms = pkg.platform_urls.iter().flat_map(|urls| {
        platform_hashes.iter().filter_map(|(plat, hash)| {
            let (template, hash) = (urls.get(*plat)?, hash.as_deref()?);
            Some(str_entry(
                *plat,
                NixValue::attrset_laid_out(
                    CollectionLayout::Inline,
                    [
                        entry("url", s(&template.replace("{version}", rel.version))),
                        entry("hash", s(hash)),
                    ],
                ),
            ))
        })
    });

    let src = NixValue::select_or(
        NixValue::ident("sources"),
        [AttrKey::Interp(NixValue::ident("system"))],
        call(
            NixValue::ident("throw"),
            [NixValue::InterpolatedStr(vec![
                StrPart::Literal(format!("{attr_name}: unsupported system ")),
                StrPart::Interp(NixValue::ident("system")),
            ])],
        ),
    );

    let derivation = attrs([
        entry("pname", s(attr_name)),
        entry("version", s(rel.version)),
        entry(
            "src",
            call(
                path(&["pkgs", "fetchurl"]),
                [NixValue::attrset_laid_out(
                    CollectionLayout::Inline,
                    [inherit(Some(NixValue::ident("src")), ["url", "hash"])],
                )],
            ),
        ),
        entry("dontUnpack", NixValue::Bool(true)),
        entry(
            "nativeBuildInputs",
            call(
                path(&["pkgs", "lib", "optionals"]),
                [
                    path(&["pkgs", "stdenv", "hostPlatform", "isLinux"]),
                    NixValue::list_laid_out(
                        CollectionLayout::Inline,
                        [path(&["pkgs", "autoPatchelfHook"])],
                    ),
                ],
            ),
        ),
        entry(
            "installPhase",
            indented(&[
                "mkdir -p $out/bin".to_string(),
                format!("cp $src $out/bin/{binary_name}"),
                format!("chmod +x $out/bin/{binary_name}"),
            ]),
        ),
        entry(
            "meta",
            attrs(description_homepage(pkg).into_iter().chain([
                entry(
                    "license",
                    nix_license(binary_license_to_nix(pkg.license.as_deref())),
                ),
                entry(
                    "platforms",
                    call(
                        path(&["builtins", "attrNames"]),
                        [NixValue::ident("sources")],
                    ),
                ),
                entry("mainProgram", s(binary_name)),
            ])),
        ),
    ]);

    NixValue::let_laid_out(
        LetLayout::BodyAfterIn,
        [bind("sources", block(platforms)), bind("src", src)],
        call(path(&["pkgs", "stdenv", "mkDerivation"]), [derivation]),
    )
}

// ---------------------------------------------------------------------------
// builds/java/default.nix, builds/csharp/default.nix
// ---------------------------------------------------------------------------

/// Generate the `builds/java/default.nix` file content from the matrix.
#[must_use]
pub fn generate_java_builds(matrix: &Matrix) -> String {
    let body = release_entries(
        matrix,
        |p| p.language == Language::Java && p.builder == Builder::MkJavaMavenPackage,
        |pkg, rel| {
            let mut entries = sourced_head(rel);
            if let Some(mh) = &rel.entry.maven_hash {
                entries.push(entry("mvnHash", s(mh)));
            }
            entries.extend(description_homepage(pkg));
            call(
                NixValue::ident("mkJavaMavenPackage"),
                [NixValue::ident("pkgs"), attrs(entries)],
            )
        },
    );
    nix_file(
        &[
            "Java/Maven package builds for akeyless repos.",
            AUTO_GENERATED,
            "Uses substrate's mkJavaMavenPackage pattern.",
        ],
        &["pkgs", "sources", "mkJavaMavenPackage"],
        block(body),
    )
}

/// Generate the `builds/csharp/default.nix` file content from the matrix.
#[must_use]
pub fn generate_csharp_builds(matrix: &Matrix) -> String {
    let body = release_entries(
        matrix,
        |p| p.language == Language::Csharp && p.builder == Builder::MkDotnetPackage,
        |pkg, rel| {
            let mut entries = sourced_head(rel);
            entries.push(rel.entry.nuget_deps_hash.as_deref().map_or_else(
                || {
                    AttrSetEntry::Comment(
                        "TODO: nugetDeps requires a deps.json path \u{2014} run `nix build` to generate"
                            .into(),
                    )
                },
                |nh| entry("nugetDeps", s(nh)),
            ));
            entries.extend(description_homepage(pkg));
            call(
                NixValue::ident("mkDotnetPackage"),
                [NixValue::ident("pkgs"), attrs(entries)],
            )
        },
    );
    nix_file(
        &[
            "C#/.NET package builds for akeyless repos.",
            AUTO_GENERATED,
            "Uses substrate's mkDotnetPackage pattern.",
        ],
        &["pkgs", "sources", "mkDotnetPackage"],
        block(body),
    )
}

/// `pname`, `version` and `src` from the source registry.
fn sourced_head(rel: &Release) -> Vec<AttrSetEntry> {
    vec![
        entry("pname", s(&rel.attr_name)),
        entry("version", source_version(&rel.src_key)),
        entry("src", source(&rel.src_key)),
    ]
}

// ---------------------------------------------------------------------------
// builds/{ruby,php,helm}/default.nix: source-only
// ---------------------------------------------------------------------------

/// A source-only builds file (packages with `builder = none`): each
/// release exposes its source, version and metadata, and no derivation.
fn source_only_builds(matrix: &Matrix, language: Language, first_line: &str) -> String {
    let body = release_entries(
        matrix,
        |p| p.language == language,
        |pkg, rel| {
            attrs(
                [
                    inherit(Some(source(&rel.src_key)), ["src"]),
                    entry("version", source_version(&rel.src_key)),
                ]
                .into_iter()
                .chain(description_homepage(pkg)),
            )
        },
    );
    nix_file(
        &[
            first_line,
            AUTO_GENERATED,
            "Source-only (no Nix builder yet).",
        ],
        &["sources"],
        block(body),
    )
}

/// Generate the `builds/ruby/default.nix` file content from the matrix.
/// Ruby packages currently use builder = none, so this emits source-only outputs.
#[must_use]
pub fn generate_ruby_builds(matrix: &Matrix) -> String {
    source_only_builds(
        matrix,
        Language::Ruby,
        "Ruby package sources for akeyless repos.",
    )
}

/// Generate the `builds/php/default.nix` file content from the matrix.
/// PHP packages currently use builder = none, so this emits source-only outputs.
#[must_use]
pub fn generate_php_builds(matrix: &Matrix) -> String {
    source_only_builds(
        matrix,
        Language::Php,
        "PHP package sources for akeyless repos.",
    )
}

/// Generate the `builds/helm/default.nix` file content from the matrix.
/// Helm charts currently use builder = none, so this emits source-only outputs.
#[must_use]
pub fn generate_helm_builds(matrix: &Matrix) -> String {
    source_only_builds(
        matrix,
        Language::Helm,
        "Helm chart sources for akeyless repos.",
    )
}

// ---------------------------------------------------------------------------
// lib/matrix-metadata.nix
// ---------------------------------------------------------------------------

/// Generate the `lib/matrix-metadata.nix` file content from the matrix.
#[must_use]
pub fn generate_matrix_metadata(matrix: &Matrix) -> String {
    // packageSourceMap: ALL versioned entries
    let mut source_map = Vec::new();
    for (pkg_name, pkg) in &matrix.packages {
        if pkg.builder == Builder::Fetchurl {
            // Binary packages use their own name as the source key, and have
            // no versioned source keys.
            if Matrix::latest_verified(pkg).is_some() {
                source_map.push(entry(pkg_name, s(pkg_name)));
            }
            continue;
        }
        for rel in releases(pkg_name, pkg) {
            source_map.push(entry(&rel.attr_name, s(&rel.src_key)));
        }
    }

    let mut body = vec![
        entry("packageSourceMap", block(source_map)),
        AttrSetEntry::Blank,
    ];
    for (tier_num, tier_name) in [
        (1, "tier1Packages"),
        (2, "tier2Packages"),
        (3, "tier3Packages"),
    ] {
        // Only packages with a buildable builder and at least one verified
        // version.
        let names = matrix
            .packages
            .iter()
            .filter(|(_, p)| {
                p.tier == tier_num
                    && p.builder != Builder::None
                    && Matrix::latest_verified(p).is_some()
            })
            .map(|(name, _)| s(name));
        body.extend(spaced(
            tier_name,
            NixValue::list_laid_out(CollectionLayout::Block, names),
        ));
    }

    render_file(&NixValue::commented(
        [
            AUTO_GENERATED,
            "Exports packageSourceMap and tier lists for flake.nix and module/default.nix.",
        ],
        block(body),
    ))
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Map a license string (e.g., "MPL-2.0") to a nixpkgs license attribute name.
fn license_to_nix(license: &str) -> &str {
    match license {
        "MPL-2.0" => "mpl20",
        "MIT" => "mit",
        "Apache-2.0" => "asl20",
        "BSD-3-Clause" => "bsd3",
        "GPL-3.0" => "gpl3Only",
        _ => "free",
    }
}

/// License attribute for a prebuilt binary: unfree unless declared.
fn binary_license_to_nix(license: Option<&str>) -> &str {
    match license {
        None | Some("unfree") => "unfree",
        Some("MIT") => "mit",
        Some("Apache-2.0") => "asl20",
        Some(_) => "free",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::matrix::{Builder, Language, Matrix, Package, Status, VersionEntry};
    use std::collections::BTreeMap;

    fn test_matrix() -> Matrix {
        let mut versions = BTreeMap::new();
        versions.insert(
            "1.0.0".to_string(),
            VersionEntry {
                rev: "abc123".into(),
                source_hash: Some("sha256-test".into()),
                vendor_hash: Some("sha256-vendor".into()),
                cargo_hash: None,
                npm_deps_hash: None,
                maven_hash: None,
                nuget_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-test".to_string(),
            Package {
                owner: "testorg".into(),
                repo: "test-repo".into(),
                language: Language::Go,
                builder: Builder::MkGoTool,
                tier: 1,
                sub_packages: Some(vec![".".into()]),
                proxy_vendor: None,
                license: None,
                description: "A test package".into(),
                homepage: "https://example.com".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: None,
                python_deps: None,
                pname_override: None,
                dont_npm_build: None,
                extra_post_install: None,
                binary_name: None,
                platform_urls: None,
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_sources_nix() {
        let matrix = test_matrix();
        let output = generate_sources_nix(&matrix);
        assert!(output.contains("mkSourceRegistry"));
        assert!(output.contains(r#"owner = "testorg"; repo = "test-repo";"#));
        assert!(output.contains(r#"hash = "sha256-test";"#));
        assert!(output.contains(r#"version = "1.0.0";"#));
    }

    #[test]
    fn test_generate_go_builds() {
        let matrix = test_matrix();
        let output = generate_go_builds(&matrix);
        assert!(output.contains("mkAkeylessTool"));
        assert!(output.contains(r#"vendorHash = "sha256-vendor";"#));
        assert!(output.contains(r#"subPackages = [ "." ];"#));
    }

    #[test]
    fn test_generate_matrix_metadata() {
        let matrix = test_matrix();
        let output = generate_matrix_metadata(&matrix);
        assert!(output.contains(r#"akeyless-test = "test";"#));
        assert!(output.contains("tier1Packages"));
        assert!(output.contains(r#""akeyless-test""#));
    }

    #[test]
    fn test_generate_go_builds_extra_post_install() {
        let mut matrix = test_matrix();
        let pkg = matrix.packages.get_mut("akeyless-test").unwrap();
        pkg.extra_post_install = Some("mv $out/bin/old $out/bin/new_v${version}".into());
        pkg.license = Some("MPL-2.0".into());

        let output = generate_go_builds(&matrix);
        assert!(output.contains("extraPostInstall = ''"));
        // ${version} should be interpolated to ${v "test"}
        assert!(output.contains(r#"${v "test"}"#));
        assert!(output.contains("license = pkgs.lib.licenses.mpl20;"));
    }

    #[test]
    fn test_generate_sources_fork_comment() {
        let mut matrix = test_matrix();
        let pkg = matrix.packages.get_mut("akeyless-test").unwrap();
        pkg.fork_of = Some("upstream/repo".into());
        pkg.fork_reason = Some("go mod tidy fix".into());

        let output = generate_sources_nix(&matrix);
        assert!(output.contains("# fork: go mod tidy fix"));
    }

    #[test]
    fn test_generate_go_builds_null_vendor_hash() {
        let mut matrix = test_matrix();
        let pkg = matrix.packages.get_mut("akeyless-test").unwrap();
        pkg.builder = Builder::MkGoLibraryCheck;
        pkg.tier = 3;
        // Remove vendor_hash to test null generation
        let ver = pkg.versions.get_mut("1.0.0").unwrap();
        ver.vendor_hash = None;

        let output = generate_go_builds(&matrix);
        assert!(output.contains("vendorHash = null;"));
        assert!(output.contains("mkAkeylessLibCheck"));
    }

    #[test]
    fn test_description_is_escaped_as_a_nix_string() {
        let mut matrix = test_matrix();
        let pkg = matrix.packages.get_mut("akeyless-test").unwrap();
        pkg.description = r#"has "quotes", ${interp} and back\slash"#.into();

        let output = generate_go_builds(&matrix);
        assert!(output.contains(r#"description = "has \"quotes\", \${interp} and back\\slash";"#));
    }

    #[test]
    fn test_go_tool_defaults_normalize_the_go_directive() {
        let output = generate_go_builds(&test_matrix());
        let (tool_defaults, rest) = output
            .split_once("mkAkeylessLibCheck = ")
            .expect("both shared-defaults wrappers are emitted");
        let tool_defaults = tool_defaults
            .split_once("mkAkeylessTool = ")
            .expect("tool wrapper precedes the library-check wrapper")
            .1;

        assert!(tool_defaults.contains(
            "    # Upstream go.mod is not ours to edit, so rewrite a bare-minor `go 1.N`\n\
             \x20   # to `go 1.N.0` at build time instead of tracing the fix on every eval.\n\
             \x20   normalizeGoDirective = true;\n\
             \x20 } // args);"
        ));
        // mkGoLibraryCheck takes no such parameter, and no package entry
        // repeats the default.
        assert_eq!(output.matches("normalizeGoDirective").count(), 1);
        assert!(!rest.contains("normalizeGoDirective"));
    }

    #[test]
    fn test_generate_go_builds_description_with_special_chars() {
        let mut matrix = test_matrix();
        let pkg = matrix.packages.get_mut("akeyless-test").unwrap();
        pkg.description = r#"Tool for "fancy" operations"#.into();

        let output = generate_go_builds(&matrix);
        assert!(output.contains(r#"description = "Tool for \"fancy\" operations";"#));
    }

    /// Helper: create a matrix with TWO verified versions for a single Go package.
    fn test_matrix_multi_version() -> Matrix {
        let mut versions = BTreeMap::new();
        versions.insert(
            "0.6.1".to_string(),
            VersionEntry {
                rev: "aaa111".into(),
                source_hash: Some("sha256-old".into()),
                vendor_hash: Some("sha256-vendorold".into()),
                cargo_hash: None,
                npm_deps_hash: None,
                maven_hash: None,
                nuget_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );
        versions.insert(
            "0.7.0".to_string(),
            VersionEntry {
                rev: "bbb222".into(),
                source_hash: Some("sha256-new".into()),
                vendor_hash: Some("sha256-vendornew".into()),
                cargo_hash: None,
                npm_deps_hash: None,
                maven_hash: None,
                nuget_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );
        // A pending version should NOT appear
        versions.insert(
            "0.8.0".to_string(),
            VersionEntry {
                rev: "ccc333".into(),
                source_hash: Some("sha256-pending".into()),
                vendor_hash: None,
                cargo_hash: None,
                npm_deps_hash: None,
                maven_hash: None,
                nuget_deps_hash: None,
                status: Status::Pending,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-test".to_string(),
            Package {
                owner: "testorg".into(),
                repo: "test-repo".into(),
                language: Language::Go,
                builder: Builder::MkGoTool,
                tier: 1,
                sub_packages: Some(vec![".".into()]),
                proxy_vendor: None,
                license: None,
                description: "A test package".into(),
                homepage: "https://example.com".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: None,
                python_deps: None,
                pname_override: None,
                dont_npm_build: None,
                extra_post_install: None,
                binary_name: None,
                platform_urls: None,
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_sources_nix_multi_version() {
        let matrix = test_matrix_multi_version();
        let output = generate_sources_nix(&matrix);

        // Latest (0.7.0) gets the bare key "test"
        assert!(output.contains("test = {"));
        assert!(output.contains(r#"version = "0.7.0";"#));
        assert!(output.contains(r#"hash = "sha256-new";"#));

        // Historical (0.6.1) gets versioned key "test-0_6_1"
        assert!(output.contains("test-0_6_1 = {"));
        assert!(output.contains(r#"version = "0.6.1";"#));
        assert!(output.contains(r#"hash = "sha256-old";"#));

        // Pending (0.8.0) should NOT appear
        assert!(!output.contains("0.8.0"));
        assert!(!output.contains("sha256-pending"));
    }

    #[test]
    fn test_generate_go_builds_multi_version() {
        let matrix = test_matrix_multi_version();
        let output = generate_go_builds(&matrix);

        // Latest gets bare name
        assert!(output.contains(r#"akeyless-test = mkAkeylessTool "test""#));
        assert!(output.contains(r#"vendorHash = "sha256-vendornew";"#));

        // Historical gets versioned name
        assert!(output.contains(r#"akeyless-test-0_6_1 = mkAkeylessTool "test-0_6_1""#));
        assert!(output.contains(r#"vendorHash = "sha256-vendorold";"#));

        // Pending should NOT appear
        assert!(!output.contains("0_8_0"));
    }

    #[test]
    fn test_generate_matrix_metadata_multi_version() {
        let matrix = test_matrix_multi_version();
        let output = generate_matrix_metadata(&matrix);

        // packageSourceMap has both entries
        assert!(output.contains(r#"akeyless-test = "test";"#));
        assert!(output.contains(r#"akeyless-test-0_6_1 = "test-0_6_1";"#));

        // Tier list only has unversioned (latest) name
        assert!(output.contains(r#""akeyless-test""#));
        // Versioned name should NOT be in tier lists
        assert!(!output.contains(r#""akeyless-test-0_6_1""#));
    }

    // ---------------------------------------------------------------------------
    // Java/Maven build tests
    // ---------------------------------------------------------------------------

    fn test_java_matrix() -> Matrix {
        let mut versions = BTreeMap::new();
        versions.insert(
            "5.0.22".to_string(),
            VersionEntry {
                rev: "javarev".into(),
                source_hash: Some("sha256-javasrc".into()),
                vendor_hash: None,
                cargo_hash: None,
                npm_deps_hash: None,
                maven_hash: Some("sha256-maven123".into()),
                nuget_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-java-sdk".to_string(),
            Package {
                owner: "akeylesslabs".into(),
                repo: "akeyless-java".into(),
                language: Language::Java,
                builder: Builder::MkJavaMavenPackage,
                tier: 3,
                sub_packages: None,
                proxy_vendor: None,
                license: None,
                description: "Akeyless Java SDK".into(),
                homepage: "https://github.com/akeylesslabs/akeyless-java".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: None,
                python_deps: None,
                pname_override: None,
                dont_npm_build: None,
                extra_post_install: None,
                binary_name: None,
                platform_urls: None,
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_java_builds() {
        let matrix = test_java_matrix();
        let output = generate_java_builds(&matrix);
        assert!(output.contains("mkJavaMavenPackage"));
        assert!(output.contains(r#"pname = "akeyless-java-sdk";"#));
        assert!(output.contains("sources.java-sdk"));
        assert!(output.contains(r#"mvnHash = "sha256-maven123";"#));
        assert!(output.contains(r#"description = "Akeyless Java SDK";"#));
    }

    #[test]
    fn test_generate_java_builds_empty_for_non_java() {
        let matrix = test_matrix();
        let output = generate_java_builds(&matrix);
        // Go packages should not appear in Java builds
        assert!(!output.contains("akeyless-test"));
        assert!(output.contains("mkJavaMavenPackage"));
    }

    // ---------------------------------------------------------------------------
    // C#/.NET build tests
    // ---------------------------------------------------------------------------

    fn test_csharp_matrix() -> Matrix {
        let mut versions = BTreeMap::new();
        versions.insert(
            "2.0.0".to_string(),
            VersionEntry {
                rev: "csrev".into(),
                source_hash: Some("sha256-cssrc".into()),
                vendor_hash: None,
                cargo_hash: None,
                npm_deps_hash: None,
                maven_hash: None,
                nuget_deps_hash: Some("sha256-nuget456".into()),
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-csharp-sdk".to_string(),
            Package {
                owner: "akeylesslabs".into(),
                repo: "akeyless-csharp".into(),
                language: Language::Csharp,
                builder: Builder::MkDotnetPackage,
                tier: 3,
                sub_packages: None,
                proxy_vendor: None,
                license: None,
                description: "Akeyless C# SDK".into(),
                homepage: "https://github.com/akeylesslabs/akeyless-csharp".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: None,
                python_deps: None,
                pname_override: None,
                dont_npm_build: None,
                extra_post_install: None,
                binary_name: None,
                platform_urls: None,
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_csharp_builds() {
        let matrix = test_csharp_matrix();
        let output = generate_csharp_builds(&matrix);
        assert!(output.contains("mkDotnetPackage"));
        assert!(output.contains(r#"pname = "akeyless-csharp-sdk";"#));
        assert!(output.contains("sources.csharp-sdk"));
        assert!(output.contains(r#"nugetDeps = "sha256-nuget456";"#));
        assert!(output.contains(r#"description = "Akeyless C# SDK";"#));
    }

    // ---------------------------------------------------------------------------
    // Ruby build tests (source-only)
    // ---------------------------------------------------------------------------

    fn test_ruby_matrix() -> Matrix {
        let mut versions = BTreeMap::new();
        versions.insert(
            "1.0.0".to_string(),
            VersionEntry {
                rev: "rubyrev".into(),
                source_hash: Some("sha256-rubysrc".into()),
                vendor_hash: None,
                cargo_hash: None,
                npm_deps_hash: None,
                maven_hash: None,
                nuget_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-ruby-sdk".to_string(),
            Package {
                owner: "akeylesslabs".into(),
                repo: "akeyless-ruby".into(),
                language: Language::Ruby,
                builder: Builder::None,
                tier: 3,
                sub_packages: None,
                proxy_vendor: None,
                license: None,
                description: "Akeyless Ruby SDK".into(),
                homepage: "https://github.com/akeylesslabs/akeyless-ruby".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: None,
                python_deps: None,
                pname_override: None,
                dont_npm_build: None,
                extra_post_install: None,
                binary_name: None,
                platform_urls: None,
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_ruby_builds() {
        let matrix = test_ruby_matrix();
        let output = generate_ruby_builds(&matrix);
        assert!(output.contains("{ sources }:"));
        assert!(output.contains("akeyless-ruby-sdk = {"));
        assert!(output.contains("inherit (sources.ruby-sdk) src;"));
        assert!(output.contains("version = sources.ruby-sdk.meta.version;"));
        assert!(output.contains(r#"description = "Akeyless Ruby SDK";"#));
    }

    // ---------------------------------------------------------------------------
    // PHP build tests (source-only)
    // ---------------------------------------------------------------------------

    fn test_php_matrix() -> Matrix {
        let mut versions = BTreeMap::new();
        versions.insert(
            "3.0.0".to_string(),
            VersionEntry {
                rev: "phprev".into(),
                source_hash: Some("sha256-phpsrc".into()),
                vendor_hash: None,
                cargo_hash: None,
                npm_deps_hash: None,
                maven_hash: None,
                nuget_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-php-sdk".to_string(),
            Package {
                owner: "akeylesslabs".into(),
                repo: "akeyless-php".into(),
                language: Language::Php,
                builder: Builder::None,
                tier: 3,
                sub_packages: None,
                proxy_vendor: None,
                license: None,
                description: "Akeyless PHP SDK".into(),
                homepage: "https://github.com/akeylesslabs/akeyless-php".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: None,
                python_deps: None,
                pname_override: None,
                dont_npm_build: None,
                extra_post_install: None,
                binary_name: None,
                platform_urls: None,
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_php_builds() {
        let matrix = test_php_matrix();
        let output = generate_php_builds(&matrix);
        assert!(output.contains("{ sources }:"));
        assert!(output.contains("akeyless-php-sdk = {"));
        assert!(output.contains("inherit (sources.php-sdk) src;"));
        assert!(output.contains(r#"description = "Akeyless PHP SDK";"#));
    }

    // ---------------------------------------------------------------------------
    // Helm build tests (source-only)
    // ---------------------------------------------------------------------------

    fn test_helm_matrix() -> Matrix {
        let mut versions = BTreeMap::new();
        versions.insert(
            "4.0.0".to_string(),
            VersionEntry {
                rev: "helmrev".into(),
                source_hash: Some("sha256-helmsrc".into()),
                vendor_hash: None,
                cargo_hash: None,
                npm_deps_hash: None,
                maven_hash: None,
                nuget_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-helm-charts".to_string(),
            Package {
                owner: "akeylesslabs".into(),
                repo: "helm-charts".into(),
                language: Language::Helm,
                builder: Builder::None,
                tier: 3,
                sub_packages: None,
                proxy_vendor: None,
                license: None,
                description: "Akeyless Helm Charts".into(),
                homepage: "https://github.com/akeylesslabs/helm-charts".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: None,
                python_deps: None,
                pname_override: None,
                dont_npm_build: None,
                extra_post_install: None,
                binary_name: None,
                platform_urls: None,
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_helm_builds() {
        let matrix = test_helm_matrix();
        let output = generate_helm_builds(&matrix);
        assert!(output.contains("{ sources }:"));
        assert!(output.contains("akeyless-helm-charts = {"));
        assert!(output.contains("inherit (sources.helm-charts) src;"));
        assert!(output.contains(r#"description = "Akeyless Helm Charts";"#));
    }

    #[test]
    fn test_generate_java_builds_in_metadata() {
        let matrix = test_java_matrix();
        let output = generate_matrix_metadata(&matrix);
        // Java packages with MkJavaMavenPackage builder should appear in packageSourceMap
        assert!(output.contains(r#"akeyless-java-sdk = "java-sdk";"#));
        // And in tier3Packages
        assert!(output.contains(r#""akeyless-java-sdk""#));
    }

    #[test]
    fn test_generate_source_only_not_in_tier_lists() {
        let matrix = test_ruby_matrix();
        let output = generate_matrix_metadata(&matrix);
        // Source-only (builder = none) packages should be in packageSourceMap
        assert!(output.contains(r#"akeyless-ruby-sdk = "ruby-sdk";"#));
        // But NOT in tier lists (builder = none is excluded)
        let tier3_section = output
            .split("tier3Packages = [")
            .nth(1)
            .unwrap()
            .split("];")
            .next()
            .unwrap();
        assert!(!tier3_section.contains("akeyless-ruby-sdk"));
    }

    // ---------------------------------------------------------------------------
    // Content-level tests: verify generated Nix output for each language
    // ---------------------------------------------------------------------------

    #[test]
    fn test_java_builds_content_verified_package() {
        let matrix = test_java_matrix();
        let output = generate_java_builds(&matrix);

        // Builder call
        assert!(output.contains("mkJavaMavenPackage pkgs {"));
        // Maven hash emitted
        assert!(output.contains(r#"mvnHash = "sha256-maven123";"#));
        // Description present
        assert!(output.contains(r#"description = "Akeyless Java SDK";"#));
        // Homepage present
        assert!(output.contains(r#"homepage = "https://github.com/akeylesslabs/akeyless-java";"#));
        // Source key derived correctly (strips akeyless- prefix)
        assert!(output.contains("sources.java-sdk.meta.version"));
        assert!(output.contains("src = sources.java-sdk;"));
    }

    #[test]
    fn test_java_builds_no_maven_hash() {
        let mut matrix = test_java_matrix();
        let pkg = matrix.packages.get_mut("akeyless-java-sdk").unwrap();
        pkg.versions.get_mut("5.0.22").unwrap().maven_hash = None;

        let output = generate_java_builds(&matrix);
        // When maven_hash is None, mvnHash should not be emitted
        assert!(!output.contains("mvnHash"));
        // But the package should still be present
        assert!(output.contains("akeyless-java-sdk"));
    }

    #[test]
    fn test_csharp_builds_content_with_nuget_deps() {
        let matrix = test_csharp_matrix();
        let output = generate_csharp_builds(&matrix);

        // Builder call
        assert!(output.contains("mkDotnetPackage pkgs {"));
        // nugetDeps emitted with correct attr name (not nugetDepsHash)
        assert!(output.contains(r#"nugetDeps = "sha256-nuget456";"#));
        assert!(!output.contains("nugetDepsHash"));
        // Description present
        assert!(output.contains(r#"description = "Akeyless C# SDK";"#));
        // Source key
        assert!(output.contains("sources.csharp-sdk.meta.version"));
        assert!(output.contains("src = sources.csharp-sdk;"));
    }

    #[test]
    fn test_csharp_builds_content_without_nuget_deps() {
        let mut matrix = test_csharp_matrix();
        let pkg = matrix.packages.get_mut("akeyless-csharp-sdk").unwrap();
        pkg.versions.get_mut("2.0.0").unwrap().nuget_deps_hash = None;

        let output = generate_csharp_builds(&matrix);
        // When nuget_deps_hash is None, emit a TODO comment
        assert!(output.contains("# TODO: nugetDeps requires a deps.json path"));
        // nugetDeps should NOT be emitted as an attribute
        assert!(!output.contains("nugetDeps ="));
        // Package should still be present
        assert!(output.contains("akeyless-csharp-sdk"));
    }

    #[test]
    fn test_ruby_builds_content_verified_package() {
        let matrix = test_ruby_matrix();
        let output = generate_ruby_builds(&matrix);

        // Source-only pattern: inherit src
        assert!(output.contains("inherit (sources.ruby-sdk) src;"));
        // Version from source registry
        assert!(output.contains("version = sources.ruby-sdk.meta.version;"));
        // Description present
        assert!(output.contains(r#"description = "Akeyless Ruby SDK";"#));
        // Homepage present
        assert!(output.contains(r#"homepage = "https://github.com/akeylesslabs/akeyless-ruby";"#));
        // Header comment
        assert!(output.contains("Source-only (no Nix builder yet)"));
        // Function signature takes only sources
        assert!(output.contains("{ sources }:"));
    }

    #[test]
    fn test_php_builds_content_verified_package() {
        let matrix = test_php_matrix();
        let output = generate_php_builds(&matrix);

        // Source-only pattern
        assert!(output.contains("inherit (sources.php-sdk) src;"));
        assert!(output.contains("version = sources.php-sdk.meta.version;"));
        // Description present
        assert!(output.contains(r#"description = "Akeyless PHP SDK";"#));
        // Homepage present
        assert!(output.contains(r#"homepage = "https://github.com/akeylesslabs/akeyless-php";"#));
        // Header comment
        assert!(output.contains("Source-only (no Nix builder yet)"));
        // Function signature
        assert!(output.contains("{ sources }:"));
    }

    #[test]
    fn test_helm_builds_content_verified_package() {
        let matrix = test_helm_matrix();
        let output = generate_helm_builds(&matrix);

        // Source-only pattern
        assert!(output.contains("inherit (sources.helm-charts) src;"));
        assert!(output.contains("version = sources.helm-charts.meta.version;"));
        // Description present
        assert!(output.contains(r#"description = "Akeyless Helm Charts";"#));
        // Homepage present
        assert!(output.contains(r#"homepage = "https://github.com/akeylesslabs/helm-charts";"#));
        // Header comment
        assert!(output.contains("Source-only (no Nix builder yet)"));
        // Attr name
        assert!(output.contains("akeyless-helm-charts = {"));
    }

    // ---------------------------------------------------------------------------
    // Rust build tests
    // ---------------------------------------------------------------------------

    fn test_rust_matrix() -> Matrix {
        let mut versions = BTreeMap::new();
        versions.insert(
            "0.3.0".to_string(),
            VersionEntry {
                rev: "rustrev".into(),
                source_hash: Some("sha256-rustsrc".into()),
                vendor_hash: None,
                cargo_hash: Some("sha256-cargo789".into()),
                npm_deps_hash: None,
                maven_hash: None,
                nuget_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-rust-tool".to_string(),
            Package {
                owner: "akeylesslabs".into(),
                repo: "rust-tool".into(),
                language: Language::Rust,
                builder: Builder::BuildRustPackage,
                tier: 2,
                sub_packages: None,
                proxy_vendor: None,
                license: None,
                description: "Akeyless Rust Tool".into(),
                homepage: "https://github.com/akeylesslabs/rust-tool".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: Some(vec!["protobuf".into(), "pkg-config".into()]),
                python_deps: None,
                pname_override: None,
                dont_npm_build: None,
                extra_post_install: None,
                binary_name: None,
                platform_urls: None,
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_rust_builds_content() {
        let matrix = test_rust_matrix();
        let output = generate_rust_builds(&matrix);
        assert!(output.contains("buildRustPackage"));
        assert!(output.contains(r#"pname = "akeyless-rust-tool";"#));
        assert!(output.contains("sources.rust-tool.meta.version"));
        assert!(output.contains("src = sources.rust-tool;"));
        assert!(output.contains(r#"cargoHash = "sha256-cargo789";"#));
        assert!(output.contains("doCheck = false;"));
        assert!(output.contains("nativeBuildInputs = [ pkgs.protobuf pkgs.pkg-config ];"));
        assert!(output.contains(r#"description = "Akeyless Rust Tool";"#));
        assert!(output.contains(r#"homepage = "https://github.com/akeylesslabs/rust-tool";"#));
        assert!(output.contains("license = pkgs.lib.licenses.asl20;"));
    }

    #[test]
    fn test_generate_rust_builds_no_cargo_hash() {
        let mut matrix = test_rust_matrix();
        let pkg = matrix.packages.get_mut("akeyless-rust-tool").unwrap();
        pkg.versions.get_mut("0.3.0").unwrap().cargo_hash = None;

        let output = generate_rust_builds(&matrix);
        assert!(!output.contains("cargoHash"));
        assert!(output.contains("akeyless-rust-tool"));
    }

    #[test]
    fn test_generate_rust_builds_no_native_inputs() {
        let mut matrix = test_rust_matrix();
        let pkg = matrix.packages.get_mut("akeyless-rust-tool").unwrap();
        pkg.native_build_inputs = None;

        let output = generate_rust_builds(&matrix);
        assert!(!output.contains("nativeBuildInputs"));
    }

    #[test]
    fn test_generate_rust_builds_empty_for_non_rust() {
        let matrix = test_matrix();
        let output = generate_rust_builds(&matrix);
        assert!(!output.contains("akeyless-test"));
        assert!(output.contains("Rust package builds"));
    }

    // ---------------------------------------------------------------------------
    // Python build tests
    // ---------------------------------------------------------------------------

    fn test_python_matrix() -> Matrix {
        let mut versions = BTreeMap::new();
        versions.insert(
            "5.0.22".to_string(),
            VersionEntry {
                rev: "pyrev".into(),
                source_hash: Some("sha256-pysrc".into()),
                vendor_hash: None,
                cargo_hash: None,
                npm_deps_hash: None,
                maven_hash: None,
                nuget_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-python-sdk".to_string(),
            Package {
                owner: "akeylesslabs".into(),
                repo: "akeyless-python".into(),
                language: Language::Python,
                builder: Builder::MkPythonPackage,
                tier: 3,
                sub_packages: None,
                proxy_vendor: None,
                license: None,
                description: "Akeyless Python SDK".into(),
                homepage: "https://github.com/akeylesslabs/akeyless-python".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: None,
                python_deps: Some(vec!["requests".into(), "urllib3".into()]),
                pname_override: Some("akeyless".into()),
                dont_npm_build: None,
                extra_post_install: None,
                binary_name: None,
                platform_urls: None,
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_python_builds_content() {
        let matrix = test_python_matrix();
        let output = generate_python_builds(&matrix);
        assert!(output.contains("mkPythonPackage pkgs {"));
        assert!(output.contains(r#"pname = "akeyless";"#));
        assert!(output.contains("sources.python-sdk.meta.version"));
        assert!(output.contains("src = sources.python-sdk;"));
        assert!(output.contains("propagatedBuildInputs = with pkgs.python3Packages; ["));
        assert!(output.contains("      requests"));
        assert!(output.contains("      urllib3"));
        assert!(output.contains(r#"description = "Akeyless Python SDK";"#));
    }

    #[test]
    fn test_generate_python_builds_no_deps() {
        let mut matrix = test_python_matrix();
        let pkg = matrix.packages.get_mut("akeyless-python-sdk").unwrap();
        pkg.python_deps = None;
        pkg.pname_override = None;

        let output = generate_python_builds(&matrix);
        assert!(!output.contains("propagatedBuildInputs"));
        assert!(output.contains(r#"pname = "akeyless-python-sdk";"#));
    }

    #[test]
    fn test_generate_python_builds_empty_for_non_python() {
        let matrix = test_matrix();
        let output = generate_python_builds(&matrix);
        assert!(!output.contains("akeyless-test"));
        assert!(output.contains("mkPythonPackage"));
    }

    // ---------------------------------------------------------------------------
    // TypeScript build tests
    // ---------------------------------------------------------------------------

    fn test_typescript_matrix() -> Matrix {
        let mut versions = BTreeMap::new();
        versions.insert(
            "2.1.0".to_string(),
            VersionEntry {
                rev: "tsrev".into(),
                source_hash: Some("sha256-tssrc".into()),
                vendor_hash: None,
                cargo_hash: None,
                npm_deps_hash: Some("sha256-npmdeps".into()),
                maven_hash: None,
                nuget_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-ts-tool".to_string(),
            Package {
                owner: "akeylesslabs".into(),
                repo: "ts-tool".into(),
                language: Language::TypeScript,
                builder: Builder::BuildNpmPackage,
                tier: 2,
                sub_packages: None,
                proxy_vendor: None,
                license: None,
                description: "Akeyless TypeScript Tool".into(),
                homepage: "https://github.com/akeylesslabs/ts-tool".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: None,
                python_deps: None,
                pname_override: None,
                dont_npm_build: Some(true),
                extra_post_install: None,
                binary_name: None,
                platform_urls: None,
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_typescript_builds_content() {
        let matrix = test_typescript_matrix();
        let output = generate_typescript_builds(&matrix);
        assert!(output.contains("buildNpmPackage"));
        assert!(output.contains(r#"pname = "akeyless-ts-tool";"#));
        assert!(output.contains("sources.ts-tool.meta.version"));
        assert!(output.contains("src = sources.ts-tool;"));
        assert!(output.contains(r#"npmDepsHash = "sha256-npmdeps";"#));
        assert!(output.contains("dontNpmBuild = true;"));
        assert!(output.contains(r#"description = "Akeyless TypeScript Tool";"#));
        assert!(output.contains("license = pkgs.lib.licenses.asl20;"));
    }

    #[test]
    fn test_generate_typescript_builds_no_npm_hash() {
        let mut matrix = test_typescript_matrix();
        let pkg = matrix.packages.get_mut("akeyless-ts-tool").unwrap();
        pkg.versions.get_mut("2.1.0").unwrap().npm_deps_hash = None;
        pkg.dont_npm_build = None;

        let output = generate_typescript_builds(&matrix);
        assert!(!output.contains("npmDepsHash"));
        assert!(!output.contains("dontNpmBuild"));
    }

    // ---------------------------------------------------------------------------
    // Binary/fetchurl build tests
    // ---------------------------------------------------------------------------

    fn test_binary_matrix() -> Matrix {
        let mut platform_urls = BTreeMap::new();
        platform_urls.insert(
            "aarch64-darwin".to_string(),
            "https://dl.example.com/{version}/bin-aarch64-darwin".to_string(),
        );
        platform_urls.insert(
            "x86_64-linux".to_string(),
            "https://dl.example.com/{version}/bin-x86_64-linux".to_string(),
        );

        let mut versions = BTreeMap::new();
        versions.insert(
            "3.5.0".to_string(),
            VersionEntry {
                rev: "binrev".into(),
                source_hash: None,
                vendor_hash: None,
                cargo_hash: None,
                npm_deps_hash: None,
                maven_hash: None,
                nuget_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: Some("sha256-darwinHash".into()),
                hash_x86_64_darwin: None,
                hash_x86_64_linux: Some("sha256-linuxHash".into()),
                hash_aarch64_linux: None,
            },
        );

        let mut packages = BTreeMap::new();
        packages.insert(
            "akeyless-cli".to_string(),
            Package {
                owner: "akeylesslabs".into(),
                repo: "akeyless-cli".into(),
                language: Language::Go,
                builder: Builder::Fetchurl,
                tier: 1,
                sub_packages: None,
                proxy_vendor: None,
                license: Some("unfree".into()),
                description: "Akeyless CLI".into(),
                homepage: "https://akeyless.io".into(),
                fork_of: None,
                fork_reason: None,
                native_build_inputs: None,
                python_deps: None,
                pname_override: None,
                dont_npm_build: None,
                extra_post_install: None,
                binary_name: Some("akeyless".into()),
                platform_urls: Some(platform_urls),
                track: crate::matrix::TrackMode::default(),
                unstable_base: None,
                versions,
            },
        );

        Matrix { packages }
    }

    #[test]
    fn test_generate_binary_builds_content() {
        let matrix = test_binary_matrix();
        let output = generate_binary_builds(&matrix);
        assert!(output.contains("stdenv.mkDerivation"));
        assert!(output.contains(r#"pname = "akeyless-cli";"#));
        assert!(output.contains(r#"version = "3.5.0";"#));
        assert!(output.contains("dontUnpack = true;"));
        assert!(output.contains("autoPatchelfHook"));
        assert!(output.contains("cp $src $out/bin/akeyless"));
        assert!(output.contains("chmod +x $out/bin/akeyless"));
        assert!(output.contains(r#"mainProgram = "akeyless";"#));
        assert!(output.contains("license = pkgs.lib.licenses.unfree;"));
    }

    #[test]
    fn test_generate_binary_builds_platform_urls_substituted() {
        let matrix = test_binary_matrix();
        let output = generate_binary_builds(&matrix);
        assert!(output.contains("https://dl.example.com/3.5.0/bin-aarch64-darwin"));
        assert!(output.contains("https://dl.example.com/3.5.0/bin-x86_64-linux"));
        assert!(output.contains(r#"hash = "sha256-darwinHash";"#));
        assert!(output.contains(r#"hash = "sha256-linuxHash";"#));
    }

    #[test]
    fn test_generate_binary_builds_empty_for_non_fetchurl() {
        let matrix = test_matrix();
        let output = generate_binary_builds(&matrix);
        assert!(!output.contains("akeyless-test"));
    }

    #[test]
    fn test_generate_binary_builds_not_in_sources() {
        let matrix = test_binary_matrix();
        let output = generate_sources_nix(&matrix);
        assert!(!output.contains("akeyless-cli"));
    }

    #[test]
    fn test_generate_binary_in_metadata() {
        let matrix = test_binary_matrix();
        let output = generate_matrix_metadata(&matrix);
        assert!(output.contains(r#"akeyless-cli = "akeyless-cli";"#));
    }

    // ---------------------------------------------------------------------------
    // license_to_nix coverage
    // ---------------------------------------------------------------------------

    #[test]
    fn test_license_to_nix_all_variants() {
        assert_eq!(license_to_nix("MPL-2.0"), "mpl20");
        assert_eq!(license_to_nix("MIT"), "mit");
        assert_eq!(license_to_nix("Apache-2.0"), "asl20");
        assert_eq!(license_to_nix("BSD-3-Clause"), "bsd3");
        assert_eq!(license_to_nix("GPL-3.0"), "gpl3Only");
        assert_eq!(license_to_nix("Unknown-License"), "free");
    }

    // ---------------------------------------------------------------------------
    // Go builds: proxy_vendor on MkGoTool
    // ---------------------------------------------------------------------------

    #[test]
    fn test_generate_go_builds_proxy_vendor() {
        let mut matrix = test_matrix();
        let pkg = matrix.packages.get_mut("akeyless-test").unwrap();
        pkg.proxy_vendor = Some(true);

        let output = generate_go_builds(&matrix);
        assert!(output.contains("proxyVendor = true;"));
    }

    // ---------------------------------------------------------------------------
    // Multi-version for Rust (older version gets sanitized key)
    // ---------------------------------------------------------------------------

    #[test]
    fn test_generate_rust_builds_multi_version() {
        let mut matrix = test_rust_matrix();
        let pkg = matrix.packages.get_mut("akeyless-rust-tool").unwrap();
        pkg.versions.insert(
            "0.2.0".to_string(),
            VersionEntry {
                rev: "oldrev".into(),
                source_hash: Some("sha256-oldsrc".into()),
                vendor_hash: None,
                cargo_hash: Some("sha256-oldcargo".into()),
                npm_deps_hash: None,
                maven_hash: None,
                nuget_deps_hash: None,
                status: Status::Verified,
                verified_at: None,
                hash_aarch64_darwin: None,
                hash_x86_64_darwin: None,
                hash_x86_64_linux: None,
                hash_aarch64_linux: None,
            },
        );

        let output = generate_rust_builds(&matrix);
        assert!(output.contains("akeyless-rust-tool ="));
        assert!(output.contains("akeyless-rust-tool-0_2_0 ="));
        assert!(output.contains(r#"cargoHash = "sha256-cargo789";"#));
        assert!(output.contains(r#"cargoHash = "sha256-oldcargo";"#));
    }

    // ---------------------------------------------------------------------------
    // Sources: fork with no fork_reason uses default "fork"
    // ---------------------------------------------------------------------------

    #[test]
    fn test_generate_sources_fork_default_reason() {
        let mut matrix = test_matrix();
        let pkg = matrix.packages.get_mut("akeyless-test").unwrap();
        pkg.fork_of = Some("upstream/repo".into());
        pkg.fork_reason = None;

        let output = generate_sources_nix(&matrix);
        assert!(output.contains("# fork: fork"));
    }

    // ---------------------------------------------------------------------------
    // Binary builds: custom binary_name vs default
    // ---------------------------------------------------------------------------

    #[test]
    fn test_generate_binary_builds_default_binary_name() {
        let mut matrix = test_binary_matrix();
        let pkg = matrix.packages.get_mut("akeyless-cli").unwrap();
        pkg.binary_name = None;

        let output = generate_binary_builds(&matrix);
        assert!(output.contains("cp $src $out/bin/akeyless-cli"));
        assert!(output.contains(r#"mainProgram = "akeyless-cli";"#));
    }

    // ---------------------------------------------------------------------------
    // Binary builds: MIT license mapping
    // ---------------------------------------------------------------------------

    #[test]
    fn test_generate_binary_builds_mit_license() {
        let mut matrix = test_binary_matrix();
        let pkg = matrix.packages.get_mut("akeyless-cli").unwrap();
        pkg.license = Some("MIT".into());

        let output = generate_binary_builds(&matrix);
        assert!(output.contains("license = pkgs.lib.licenses.mit;"));
    }
}
